/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as HelpRouteImport } from './routes/help'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated.history'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as AuthenticatedToolsChatRouteImport } from './routes/_authenticated.tools.chat'
import { Route as AuthenticatedToolsEmailRouteImport } from './routes/_authenticated.tools.email'
import { Route as AuthenticatedToolsPlannerRouteImport } from './routes/_authenticated.tools.planner'
import { Route as AuthenticatedToolsResearchRouteImport } from './routes/_authenticated.tools.research'
import { Route as AuthenticatedToolsSummarizerRouteImport } from './routes/_authenticated.tools.summarizer'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedToolsChatRoute = AuthenticatedToolsChatRouteImport.update({
  id: '/tools/chat',
  path: '/tools/chat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedToolsEmailRoute = AuthenticatedToolsEmailRouteImport.update({
  id: '/tools/email',
  path: '/tools/email',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedToolsPlannerRoute =
  AuthenticatedToolsPlannerRouteImport.update({
    id: '/tools/planner',
    path: '/tools/planner',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedToolsResearchRoute =
  AuthenticatedToolsResearchRouteImport.update({
    id: '/tools/research',
    path: '/tools/research',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedToolsSummarizerRoute =
  AuthenticatedToolsSummarizerRouteImport.update({
    id: '/tools/summarizer',
    path: '/tools/summarizer',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/tools/chat': typeof AuthenticatedToolsChatRoute
  '/tools/email': typeof AuthenticatedToolsEmailRoute
  '/tools/planner': typeof AuthenticatedToolsPlannerRoute
  '/tools/research': typeof AuthenticatedToolsResearchRoute
  '/tools/summarizer': typeof AuthenticatedToolsSummarizerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/tools/chat': typeof AuthenticatedToolsChatRoute
  '/tools/email': typeof AuthenticatedToolsEmailRoute
  '/tools/planner': typeof AuthenticatedToolsPlannerRoute
  '/tools/research': typeof AuthenticatedToolsResearchRoute
  '/tools/summarizer': typeof AuthenticatedToolsSummarizerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/tools/chat': typeof AuthenticatedToolsChatRoute
  '/_authenticated/tools/email': typeof AuthenticatedToolsEmailRoute
  '/_authenticated/tools/planner': typeof AuthenticatedToolsPlannerRoute
  '/_authenticated/tools/research': typeof AuthenticatedToolsResearchRoute
  '/_authenticated/tools/summarizer': typeof AuthenticatedToolsSummarizerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/help'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/history'
    | '/profile'
    | '/tools/chat'
    | '/tools/email'
    | '/tools/planner'
    | '/tools/research'
    | '/tools/summarizer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/help'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/history'
    | '/profile'
    | '/tools/chat'
    | '/tools/email'
    | '/tools/planner'
    | '/tools/research'
    | '/tools/summarizer'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/help'
    | '/login'
    | '/register'
    | '/_authenticated/dashboard'
    | '/_authenticated/history'
    | '/_authenticated/profile'
    | '/_authenticated/tools/chat'
    | '/_authenticated/tools/email'
    | '/_authenticated/tools/planner'
    | '/_authenticated/tools/research'
    | '/_authenticated/tools/summarizer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tools/chat': {
      id: '/_authenticated/tools/chat'
      path: '/tools/chat'
      fullPath: '/tools/chat'
      preLoaderRoute: typeof AuthenticatedToolsChatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tools/email': {
      id: '/_authenticated/tools/email'
      path: '/tools/email'
      fullPath: '/tools/email'
      preLoaderRoute: typeof AuthenticatedToolsEmailRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tools/planner': {
      id: '/_authenticated/tools/planner'
      path: '/tools/planner'
      fullPath: '/tools/planner'
      preLoaderRoute: typeof AuthenticatedToolsPlannerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tools/research': {
      id: '/_authenticated/tools/research'
      path: '/tools/research'
      fullPath: '/tools/research'
      preLoaderRoute: typeof AuthenticatedToolsResearchRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tools/summarizer': {
      id: '/_authenticated/tools/summarizer'
      path: '/tools/summarizer'
      fullPath: '/tools/summarizer'
      preLoaderRoute: typeof AuthenticatedToolsSummarizerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedToolsChatRoute: typeof AuthenticatedToolsChatRoute
  AuthenticatedToolsEmailRoute: typeof AuthenticatedToolsEmailRoute
  AuthenticatedToolsPlannerRoute: typeof AuthenticatedToolsPlannerRoute
  AuthenticatedToolsResearchRoute: typeof AuthenticatedToolsResearchRoute
  AuthenticatedToolsSummarizerRoute: typeof AuthenticatedToolsSummarizerRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedToolsChatRoute: AuthenticatedToolsChatRoute,
  AuthenticatedToolsEmailRoute: AuthenticatedToolsEmailRoute,
  AuthenticatedToolsPlannerRoute: AuthenticatedToolsPlannerRoute,
  AuthenticatedToolsResearchRoute: AuthenticatedToolsResearchRoute,
  AuthenticatedToolsSummarizerRoute: AuthenticatedToolsSummarizerRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
